[package]
name = "cmini-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = "1.0.197"
serde_json = "1.0.115"
strsim = "0.11.0"
lazy_static = "1.4.0"
rayon = "1.10.0"

[dependencies.serenity]
version = "0.11.7"
default-features = false
features = ["client", "gateway", "model", "rustls_backend"]
